### ISSUE TITLE
ERROR while loading extension

### ISSUE THREAD

**Issue by schmittr** [michelp/pgjwt#1]
I get the following error when loading the plugin:
```
CREATE EXTENSION IF NOT EXISTS pgjwt;
ERROR:  transaction control statements are not allowed within an extension script
```

**Comment by michelp** [comment]
Hi @schmittr I didn't even see this issue until you closed it, sorry I wasn't paying attention I didn't even know anyone was using this code. :)

Most recent changes as you may see turn it into a real extension.  Thanks for trying it out!
