### ISSUE TITLE
Can pgrypto supports RS256?

### ISSUE THREAD

**Issue by nuevoleonkx** [michelp/pgjwt#14]
#Question

I made some examples and everything goes well, except when I move to RS256 algorithm which some applications use currently, So I'mm wondering if is fully supported by pgcypto. I cannot find anything related. 

Thanks

**Comment by Timonzimm** [comment]
+1

**Comment by michelp** [comment]
Unfortunately pgcrypto does not support public key signing.

**Comment by surprisetalk** [comment]
@michelp Any potential updates here, given the wonderful work with `pgsodium`? Willing to help too, if you point me in the right direction :)
