### ISSUE TITLE
Install on RDS or Aurora

### ISSUE THREAD

**Issue by msageryd** [michelp/pgjwt#4]
Thank you!
This is exactly what I need. But I will move to Amazon RDS or possibly the new Aurora service when I go into production. I suppose it will be hard (impossible?) to install pgjwt on these services, wouldn't it?

Please advise on how to install on Amazon if possible.

**Comment by msageryd** [comment]
Follow up..
I created the JWT functions manually as per https://github.com/larsar/postgres-jwt-prototype. It seems to work fine.

Are there any drawbacks to not use the make-script and install the functions as an extension?

**Comment by michelp** [comment]
No drawbacks, pgjwt is pure sql and can just be copied into any sql script.
