### ISSUE TITLE
how would this work on windows?

### ISSUE THREAD

**Issue by barbalex** [michelp/pgjwt#7]
How would someone working on windows install pgjwt?

**Comment by barbalex** [comment]
I got so far:

1. install make for window (http://gnuwin32.sourceforge.net/packages/make.htm)
2. add C:\Program Files (x86)\GnuWin32\bin to path
3. run `make install`

But then I get:

    PS C:\Users\alex\pgjwt> make install
    /usr/bin/mkdir -p 'C:/PROGRA~1/POSTGR~1/pg96/share/POSTGR~1/extension'
    process_begin: CreateProcess(NULL, /usr/bin/mkdir -p C:/PROGRA~1/POSTGR~1/pg96/share/POSTGR~1/extension, ...) failed.
    make (e=2): Das System kann die angegebene Datei nicht finden.
    make: *** [installdirs] Fehler 2
    PS C:\Users\alex\pgjwt>

**Comment by barbalex** [comment]
seems that extensions are in `C:\Program Files\PostgreSQL\9.6\share\extension` on my machine

**Comment by barbalex** [comment]
by the way: this is Windows 10 up to date

**Comment by barbalex** [comment]
oh well: `/usr/bin/mkdir` will of course not work

**Comment by michelp** [comment]
I'm sorry, I don't know anything about windows or how one would get pg extensions working on it.   However, you can simply remove the first line of code from pgjwt-0.0.1.sql and paste the sql code into your postgres and you will have the functions you need.  the code is pure sql so there isn't really a hard requirement to use the extension installation mechanism.

**Comment by barbalex** [comment]
Yep, that works well. Thanks a lot.
